In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [14]:
def sigmoid_derivative(x):
    return x*(1-x)

In [25]:
tranning_ip = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])

In [22]:
tranning_op = np.array([[0,0,0,0,1,1,1,1]]).T
np.random.seed(1)

In [23]:
synaptic_weights = 2*np.random.random((3,1))-1

In [24]:
print("random starting synaptic weights:")

random starting synaptic weights:


In [19]:
print(synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [26]:
for iteraion in range(20000):
    input_layer=tranning_ip
    output_layer=tranning_op
    outputs=sigmoid(np.dot(input_layer,synaptic_weights))
    error = output_layer - outputs
    adjustments=error*sigmoid_derivative(outputs)
    synaptic_weights +=np.dot(input_layer.T,adjustments)

In [27]:
print("synaptic weights after tranning")
print(synaptic_weights)
print("output after tranning:")
print(outputs)

synaptic weights after tranning
[[13.87534322]
 [-4.57643978]
 [-4.57643978]]
output after tranning:
[[5.00000000e-01]
 [1.01868947e-02]
 [1.01868947e-02]
 [1.05908603e-04]
 [9.99999058e-01]
 [9.99908479e-01]
 [9.99908479e-01]
 [9.91184927e-01]]
